<?php echo $this->doctype()->setDoctype('HTML5'); ?>

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
  <title><?php echo isset($this->title) ? $this->vars()->escape($this->title) . ' - ' : ''; ?>Zend Framework Tutorial</title>
  <?php echo $this->headLink()->prependStylesheet('/css/site.css') ?>

</head>
<body>
<div id="content">
<?php 
    echo $this->vars()->getRawValue('content');
?>

</div>
</body>
</html>
