<?php 
$title = 'My albums';
$this->title = $title;
?>
<h1><?php echo $this->vars()->escape($title); ?></h1>
<p><a href="<?php echo $this->url(array('controller'=>'album', 
        'action'=>'add'), array('name' => 'default'));?>">Add new album</a></p>

<table>
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->albums as $album) : ?>
<tr>
    <td><?php echo $this->vars()->escape($album->title);?></td>
    <td><?php echo $this->vars()->escape($album->artist);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'album', 
            'action'=>'edit'), array('name' => 'default')) . '?id=' . $album->id ;?>">Edit</a>
        <a href="<?php echo $this->url(array('controller'=>'album', 
            'action'=>'delete'), array('name' => 'default')) . '?id=' . $album->id ;?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>