<h1>An error occurred</h1>
<h2><?php echo $this->vars('message') ?></h2>

<?php 
if (!$this->vars('display_exceptions')) {
    echo "<p>Display exceptions is disabled</p>\n";
    return;
}
$exception = $this->vars('exception');
if (!$exception instanceof \Exception) {
    echo "<p>Invalid exception found</p>\n";
    return;
}
?>
<h3>Exception information:</h3>
<p>
    <b>Message:</b> <?php echo $this->vars()->escape($exception->getMessage()) ?>
</p>

<h3>Stack trace:</h3>
<pre><?php echo $exception->getTraceAsString() ?>
</pre>
